# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev linux-headers

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Create the missing package directory required by setuptools
RUN mkdir -p mcp_gsc && echo "# empty package to satisfy setuptools package definition" > mcp_gsc/__init__.py

# Upgrade pip and install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir .

# Expose a port for future use (not used by the stdio transport)
EXPOSE 8000

# Run the MCP server via stdio transport
CMD ["python", "gsc_server.py"]
